name = "physics-lab"                     # Worker 名称
compatibility_date = "2025-12-03"

type = "javascript"

[build]
command = "pnpm run build"               # 构建命令

[assets]
directory = "./dist"                      # Vite 构建输出目录
